const fs = require('fs');
const path = require('path');

// We will build the 200 database with comprehensive lore and data
const outputFilePath = path.join(__dirname, 'ruleta-prendido-fuego', 'data_celebrities.js');

const buildScriptPath = path.join(__dirname, 'ruleta-prendido-fuego', 'generator_200.js');

fs.writeFileSync(buildScriptPath, `
const fs = require('fs');
const path = require('path');

const CELEBRITIES = [
  // 1. MESA PRENDIDO FUEGO & LORE (4)
  {
    id: "tomas-holder",
    name: "Tomás Holder",
    category: "gh",
    categoryLabel: "Prendido Fuego / Gym Bro",
    tag: "Macho Alfa de Rosario",
    quote: "Mi mujer no es un hotel, es un hogar.",
    bio: "Primer expulsado y más icónico de GH. Amante de la noche, anabólicos, mewing y soltar factos cancelables.",
    lore: "El rey del contenido divisivo. Saltó a la fama en TikTok mostrando su físico y un personaje de rugbier clasista. Tras GH protagonizó romances escandalosos, internaciones por excesos, videos íntimos filtrados y una transformación espiritual que convive con su ego de gimnasio.",
    image: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=500&auto=format&fit=crop&q=80",
    auraScore: 7.8,
    caretaScore: 8.5
  },
  {
    id: "diane-caracchi",
    name: "Diane Caracchi",
    category: "farandula",
    categoryLabel: "Prendido Fuego / Conductora",
    tag: "El Ancla Moral & Monógama",
    quote: "Sos un cinco códigos, Tomás.",
    bio: "Modelo y estudiante de RR.PP. 8 años de novia, 2 de convivencia. Defensora a ultranza de la fidelidad.",
    lore: "Representa la voz de la razón y los límites inquebrantables en la mesa. No le perdona una sola infidelidad a la farándula, destruye a los jugadores de fútbol sin códigos y le pone los puntos a Holder cada vez que derrapa al aire.",
    image: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=500&auto=format&fit=crop&q=80",
    auraScore: 9.1,
    caretaScore: 2.3
  },
  {
    id: "luli-case",
    name: "Luli Casé Rossi",
    category: "farandula",
    categoryLabel: "Prendido Fuego / Conductora",
    tag: "La Migajera con Tarot",
    quote: "Esperé 2 años a un pibe y se comió a otra en Miami.",
    bio: "Conductora histriónica, astróloga de cabecera y experta en conformarse con migajas de amor por idealización.",
    lore: "El corazón sensible de Prendido Fuego. Conoce todas las red flags porque cayó en todas. Tira las cartas del tarot en vivo, analiza las cartas natales de los famosos y confiesa sus fracasos amorosos sin filtro para salvar a las oyentes.",
    image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=500&auto=format&fit=crop&q=80",
    auraScore: 8.9,
    caretaScore: 1.8
  },
  {
    id: "gisela-holder",
    name: "Gisela Gordillo (Mamá de Holder)",
    category: "farandula",
    categoryLabel: "Prendido Fuego / Lore",
    tag: "La Señora de los Factos",
    quote: "A los hombres hay que tenerlos cortitos.",
    bio: "Podóloga de Rosario, madre de Tomás y protagonista de rumores picantes con mediáticos.",
    lore: "Se convirtió en una estrella mediática propia durante el paso de Tomás por GH. Su fuerte personalidad, belleza y romances con figuras del espectáculo (como Martín Ku y mediáticos porteños) revolucionaron los programas de chimentos.",
    image: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=500&auto=format&fit=crop&q=80",
    auraScore: 8.4,
    caretaScore: 6.9
  },

  // 2. GRAN HERMANO & REALITIES (30)
  {
    id: "furia-scaglione",
    name: "Juliana 'Furia' Scaglione",
    category: "gh",
    categoryLabel: "Gran Hermano / Fenómeno Social",
    tag: "El Huracán Calvo de GH",
    quote: "¡Cariños! A la final no llegás.",
    bio: "La jugadora más disruptiva e intensa de la historia del reality en Argentina.",
    lore: "Marcó un antes y un después en la televisión abierta. Con la cabeza rapada, gritos de guerra, tácticas de desgaste psicológico y un fandom militarizado ('Los Furiosos'), dominó el rating durante 7 meses. Enfrentada con Telefe y panelistas tradicionales.",
    image: "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=500&auto=format&fit=crop&q=80",
    auraScore: 9.9,
    caretaScore: 1.5
  },
  {
    id: "coty-romero",
    name: "Coty Romero",
    category: "gh",
    categoryLabel: "Gran Hermano / Estratega",
    tag: "La Cuchillera Correntina",
    quote: "Que se vacha, que se vacha.",
    bio: "Autora de la espontánea más icónica a sus amigas. Figura del streaming y la farándula joven.",
    lore: "Revolucionó GH 2022 con su juego maquiavélico y su osito de peluche. Tras salir de la casa protagonizó separaciones dolorosas (El Conejo), ataques de pánico superados, pases por el Bailando y un romance mediático con Nacho Castañares.",
    image: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=500&auto=format&fit=crop&q=80",
    auraScore: 9.2,
    caretaScore: 6.8
  },
  {
    id: "marcos-ginocchio",
    name: "Marcos Ginocchio (El Primo)",
    category: "gh",
    categoryLabel: "Gran Hermano / Ganador",
    tag: "El Santo de Salta & Aura Pura",
    quote: "Gracias a todos, los quiero mucho.",
    bio: "Ganador indiscutido de GH 2022 con más del 70% de votos positivos. Modelo de alta costura.",
    lore: "El arquetipo de la paz absoluta. En una casa llena de peleas y traición, ganó sin levantar la voz, adoptando a la perra Mora y manteniendo su humildad. Tras el reality rechazó el conventillo televisivo para triunfar en la moda internacional.",
    image: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=500&auto=format&fit=crop&q=80",
    auraScore: 10.0,
    caretaScore: 1.0
  },
  {
    id: "alfa-gh",
    name: "Walter 'Alfa' Santiago",
    category: "gh",
    categoryLabel: "Gran Hermano / Leyenda Bizarra",
    tag: "El Patriarca de la Bandana",
    quote: "¡Acá mando yo, nene! Yo vi a Spinetta en Obras.",
    bio: "El veterano más polémico del reality. Amante de los autos clásicos y las anécdotas incomprobables.",
    lore: "Con su bandana y su overol, Alfa polarizó al país. Asegura haber cenado con todas las estrellas de Hollywood y la política de los últimos 40 años. Protagonizó peleas memorables con Ariel, romances con chicas 40 años menores y visitas al hospital por estrés mediático.",
    image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=500&auto=format&fit=crop&q=80",
    auraScore: 7.9,
    caretaScore: 8.9
  },
  {
    id: "nacho-castanares",
    name: "Nacho Castañares",
    category: "gh",
    categoryLabel: "Gran Hermano / Subcampeón & Streamer",
    tag: "El Galán de Almagro & Luzu",
    quote: "La jugada fue limpia, las cartas están sobre la mesa.",
    bio: "Subcampeón de GH 2022, conductor de streaming en Telefe y figura del canal Luzu TV.",
    lore: "Empezó formando 'Los Monitos' con Holder y terminó siendo uno de los favoritos de la gente por su madurez tras la pérdida de su madre. Tras separarse de La Tora blanqueó romance con Coty Romero generando el mayor bardo de ex compañeros.",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&auto=format&fit=crop&q=80",
    auraScore: 8.6,
    caretaScore: 3.8
  },
  {
    id: "julieta-poggio",
    name: "Julieta Poggio",
    category: "gh",
    categoryLabel: "Gran Hermano / Actriz & Modelo",
    tag: "La Diva Pop: Fuera Malas Vibras",
    quote: "¡Fuera malas vibras! #SeCaeElPersonaje.",
    bio: "Tercer puesto de GH 2022. Estrella de teatro, espectáculos infantiles y reina de la moda joven.",
    lore: "Su frase '#SeCaeElPersonaje' en el confesionario fue viral nacional. Triunfó en la calle Corrientes de la mano de José María Muscari en 'Coqueluche' y Fuerza Bruta, consolidándose como la ex Gran Hermano más exitosa en la industria del espectáculo.",
    image: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=500&auto=format&fit=crop&q=80",
    auraScore: 9.3,
    caretaScore: 2.5
  },
  {
    id: "martin-ku",
    name: "Martín Ku (El Chino)",
    category: "gh",
    categoryLabel: "Gran Hermano / Líder Supremo",
    tag: "El Rey de la Residencia & El Bro",
    quote: "Ganamos la casa, el perro y el liderazgo.",
    bio: "Récord histórico de liderazgos ganados en GH. Se llevó la casa prefabricada y al perro Arturo.",
    lore: "Estratega implacable de 'Los Bro'. Ganó casi todas las pruebas físicas y de ingenio. Afuera de la casa protagonizó rumores de romance con la mamá de Holder (Gisela Gordillo) que casi dinamitan su relación con su novia Marisol.",
    image: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=500&auto=format&fit=crop&q=80",
    auraScore: 8.7,
    caretaScore: 5.1
  },
  {
    id: "bautista-mascia",
    name: "Bautista Mascia",
    category: "gh",
    categoryLabel: "Gran Hermano / Ganador 2024",
    tag: "El Campeón Oriental del Pop",
    quote: "Tranqui, todo se acomoda solo.",
    bio: "Músico uruguayo (ex Toco Para Vos) y ganador de Gran Hermano 2024.",
    lore: "Ganó la edición más violenta y ruidosa jugando en silencio, componiendo canciones en la guitarra y manteniendo un romance limpio con Denisse González. Tras salir llenó un Teatro Gran Rex con su música.",
    image: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=500&auto=format&fit=crop&q=80",
    auraScore: 8.5,
    caretaScore: 2.9
  },
  {
    id: "emmanuel-vich",
    name: "Emmanuel Vich",
    category: "gh",
    categoryLabel: "Gran Hermano / Subcampeón 2024",
    tag: "El Ícono Glam & Make Up",
    quote: "¡Icónica, perra, devoraste!",
    bio: "Peluquero cordobés, aliado incondicional de Furia y finalista de GH 2024.",
    lore: "Atravesó todas las placas de nominación recibiendo ataques feroces pero respondiendo con looks de alta costura, maquillaje y lealtad ciega a Furia. Su marido militar y sus escándalos de celos con famosos nutrieron horas de stream.",
    image: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=500&auto=format&fit=crop&q=80",
    auraScore: 8.8,
    caretaScore: 4.2
  },
  {
    id: "virginia-demo",
    name: "Virginia Demo",
    category: "gh",
    categoryLabel: "Gran Hermano / Comediante",
    tag: "La Standapera de las Botas Altas",
    quote: "¡Hagan lo que se les cante el orto, yo me voy a llorar!",
    bio: "Comediante platense que entró como reemplazo y se convirtió en ícono viral de memes.",
    lore: "Famosa por sus botas bucaneras rojas, sus llantos espontáneos que se transformaban en risas y su rol como 'Mamá' de la casa. Protagonizó la obra musical 'Legalmente Rubia' en calle Corrientes demostrando un talento teatral intacto.",
    image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=500&auto=format&fit=crop&q=80",
    auraScore: 9.1,
    caretaScore: 1.2
  },
  {
    id: "rosina-beltran",
    name: "Rosina Beltrán",
    category: "gh",
    categoryLabel: "Gran Hermano / Modelo",
    tag: "La Inocencia Extrema & Pies",
    quote: "¿Me dejás chuparte los dedos del pie?",
    bio: "Influencer uruguaya. Amante de la energía positiva, las mariposas y los fetiches de pies.",
    lore: "Su comportamiento infantil y sus insólitos fetiches de lamerle los dedos de los pies a sus compañeros desconcertaron a la audiencia. Afuera demostró un magnetismo impresionante en marcas de moda y campañas globales.",
    image: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=500&auto=format&fit=crop&q=80",
    auraScore: 8.0,
    caretaScore: 6.4
  },
  {
    id: "manzana-big-apple",
    name: "Manzana / Big Apple (Federico Farías)",
    category: "gh",
    categoryLabel: "Gran Hermano / Músico RKT",
    tag: "El Rey de 'Que a Pasao'",
    quote: "Solamente me queda decirles una cosa... ¡Que a pasao!",
    bio: "Pionero del RKT tucumano con millones de reproducciones y protagonista de GH 2024.",
    lore: "Hizo historia con su discurso en vivo frente a toda la casa donde le declaró la guerra a Furia mirándola a los ojos. Su carisma de barrio y su bondad lo convirtieron en un personaje entrañable del streaming.",
    image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=500&auto=format&fit=crop&q=80",
    auraScore: 8.8,
    caretaScore: 2.0
  },
  {
    id: "lisandro-navarro",
    name: "Lisandro Navarro (Licha)",
    category: "gh",
    categoryLabel: "Gran Hermano / Asesor Financiero",
    tag: "El Galán del Rodete & Gym",
    quote: "La educación y el físico ante todo.",
    bio: "Asesor financiero, cocinero oficial de GH 2024 y víctima principal de los ataques de Furia.",
    lore: "Su porte hegemónico y su estilo maduro lo convirtieron en el rival número uno de Furia, con quien mantuvo un juego de atracción-odio televisivo histórico. Actualmente modelo y conductor de streamings deportivos.",
    image: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=500&auto=format&fit=crop&q=80",
    auraScore: 8.2,
    caretaScore: 4.8
  },
  {
    id: "la-tora-lucila",
    name: "Lucila 'La Tora' Villar",
    category: "gh",
    categoryLabel: "Gran Hermano / Conductora Streaming",
    tag: "La Leona de Berazategui",
    quote: "A mí con careteadas no me vengas.",
    bio: "Ex participante de GH 2022 y conductora del streaming oficial 'Fuera de Joda' y 'La Noche de los Ex'.",
    lore: "Entró con furia, fue eliminada, aprendió de sus errores y volvió para ser una de las mejores jugadoras. Hoy es una de las conductoras más profesionales del universo Telefe, manejando con carisma las entrevistas a los eliminados.",
    image: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=500&auto=format&fit=crop&q=80",
    auraScore: 8.9,
    caretaScore: 2.1
  },
  {
    id: "cata-gorostidi",
    name: "Catalina Gorostidi",
    category: "gh",
    categoryLabel: "Gran Hermano / Médica Pediatra",
    tag: "La Botinera Médica",
    quote: "Me comí a medio plantel de fútbol y qué.",
    bio: "Médica pediatra de Santa Fe, hija del futbolista 'Loco' Gorostidi y líder de 'Las Furiosas'.",
    lore: "No tiene pelos en la lengua para ventilar romances con campeones del mundo y futbolistas de primera división. Su alianza y posterior guerra a muerte con Furia marcó los picos de rating más altos de la televisión en 2024.",
    image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=500&auto=format&fit=crop&q=80",
    auraScore: 8.7,
    caretaScore: 3.5
  },
  {
    id: "sabrina-cortez",
    name: "Sabrina Cortez",
    category: "gh",
    categoryLabel: "Gran Hermano / Contadora & Modelo",
    tag: "La Rubia de los 8 Años de Novia",
    quote: "Entré de novia pero la casa te confunde.",
    bio: "Contadora pública mendocina. Ganó la primera prueba del líder y desató un escándalo de infidelidad.",
    lore: "Entró presumiendo 8 años de noviazgo formal y a las dos semanas estaba a los besos bajo las sábanas con Alan Simone. Su ruptura pública con su ex Brian Fernández y su relación tóxica posterior con Alan alimentaron programas de chimentos.",
    image: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=500&auto=format&fit=crop&q=80",
    auraScore: 7.3,
    caretaScore: 7.9
  },
  {
    id: "daniela-celis",
    name: "Daniela Celis (Pestañela / Vengañela)",
    category: "gh",
    categoryLabel: "Gran Hermano / Influencer & Madre",
    tag: "Pestañela: Ojo por Ojo",
    quote: "Fui Daniela, fui Pestañela y ahora soy Vengañela.",
    bio: "Ex GH 2022, madre de gemelas con Thiago Medina y dueña de su propio centro de estética.",
    lore: "Fue traicionada por Thiago Medina, el público la eliminó y la volvió a meter por repechaje para ejecutar una venganza televisiva implacable ('Vengañela'). El destino los unió afuera, tuvieron gemelas y construyeron una familia hermosa y millonaria.",
    image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=500&auto=format&fit=crop&q=80",
    auraScore: 9.0,
    caretaScore: 3.0
  },
  {
    id: "thiago-medina",
    name: "Thiago Medina",
    category: "gh",
    categoryLabel: "Gran Hermano / Emprendedor",
    tag: "El Chico del Mercado Central",
    quote: "La vida me dio una oportunidad y la voy a aprovechar.",
    bio: "De juntar cartón y trabajar en el Mercado Central a ser una de las figuras más queridas de Argentina.",
    lore: "Emocionó al país con su historia de superación. Dentro de la casa fue un titán en las pruebas físicas. Afuera montó una verdulería propia, compró su casa y junto a Daniela Celis formó una de las parejas más estables del espectáculo.",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&auto=format&fit=crop&q=80",
    auraScore: 9.4,
    caretaScore: 1.1
  },
  {
    id: "romina-uhrig",
    name: "Romina Uhrig",
    category: "gh",
    categoryLabel: "Gran Hermano / Ex Diputada",
    tag: "La Cocinera del Poder",
    quote: "Yo cocino para todos pero a mis hijas no me las toca nadie.",
    bio: "Ex diputada nacional, semifinalista de GH 2022 y panelista de televisión.",
    lore: "Manejó la cocina y la disciplina de GH 2022 con mano de hierro. Sus idas y vueltas con el ex intendente Walter Festa, investigaciones judiciales y romances con jóvenes de la farándula la mantienen en agenda constante.",
    image: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=500&auto=format&fit=crop&q=80",
    auraScore: 7.5,
    caretaScore: 8.2
  },
  {
    id: "agustin-guardis",
    name: "Agustín Guardis (Frodo)",
    category: "gh",
    categoryLabel: "Gran Hermano / Estratega Digital",
    tag: "El León de La Plata",
    quote: "La jugada maestra recién comienza.",
    bio: "Analista político, streamer y creador de 'La Frodoneta'.",
    lore: "Pasó de ser el más apoyado del país (apoyado por el Kun Agüero, Bizarrap y Duki) a ser cancelado masivamente en una semana por comentarios desafortunados sobre guardar fotos íntimas. Hoy exitoso streamer de gaming.",
    image: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=500&auto=format&fit=crop&q=80",
    auraScore: 7.2,
    caretaScore: 6.5
  },
  {
    id: "alexis-conejo",
    name: "Alexis Quiroga (El Conejo)",
    category: "gh",
    categoryLabel: "Gran Hermano / Actor & Productor",
    tag: "El Gaucho de General Cabrera",
    quote: "El juego del silencio es el más letal.",
    bio: "Productor agropecuario cordobés, ex GH 2022 y protagonista de teatro en calle Corrientes.",
    lore: "El cerebro oculto de GH 2022 detrás de las jugadas de Coty Romero. Tras la escandalosa separación de Coty con audios y videos de boliches filtrados, se dedicó a la actuación y el teatro con gran éxito.",
    image: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=500&auto=format&fit=crop&q=80",
    auraScore: 8.1,
    caretaScore: 5.9
  },
  {
    id: "denisse-gonzalez",
    name: "Denisse González",
    category: "gh",
    categoryLabel: "Gran Hermano / Modelo Patagónica",
    tag: "La Bella Durmiente de Trelew",
    quote: "Dormí mucho al principio pero me desperté con todo.",
    bio: "Estudiante de abogacía de Chubut, modelo y pareja de Bautista Mascia.",
    lore: "Viralizada al inicio por pasar horas durmiendo, fue reingresada por la 'Golden Ticket' y demostró una astucia letal jugando con la fulminante. Su noviazgo con Bautista es uno de los más shippeados en redes.",
    image: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=500&auto=format&fit=crop&q=80",
    auraScore: 8.3,
    caretaScore: 3.2
  },
  {
    id: "florencia-regidor",
    name: "Florencia Regidor",
    category: "gh",
    categoryLabel: "Gran Hermano / Modelo",
    tag: "La Rubia Sin Bañar",
    quote: "No me gusta bañarme todos los días, ¿cuál es el problema?",
    bio: "Modelo de Temperley que revolucionó GH 2024 con su sinceridad higiénica.",
    lore: "Entró diciendo que no le gustaba lavarse el pelo a diario y enamoró a Nico Grosman. Tras el final de GH sufrió la peor infidelidad mediática cuando Grosman la engañó con Lucía Maidana en un viaje a Uruguay.",
    image: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=500&auto=format&fit=crop&q=80",
    auraScore: 8.6,
    caretaScore: 2.8
  },
  {
    id: "mauro-dalessio",
    name: "Mauro D'Alessio",
    category: "gh",
    categoryLabel: "Gran Hermano / Rugby & Marketing",
    tag: "El Galán del Choque",
    quote: "No le tengo miedo a los gritos de nadie.",
    bio: "Ex rugbier y empleado de marketing. Protagonista del romance más explosivo con Furia.",
    lore: "Entró como reemplazo y mantuvo una relación de altísimo voltaje sexual con Furia que terminó en empujones, gritos desmedidos en el comedor y sanciones históricas de Gran Hermano.",
    image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=500&auto=format&fit=crop&q=80",
    auraScore: 7.9,
    caretaScore: 5.5
  },
  {
    id: "zoe-bogach",
    name: "Zoe Bogach",
    category: "gh",
    categoryLabel: "Gran Hermano / Chica Recoleta",
    tag: "La Barbie de Recoleta",
    quote: "Ay gordi, no sé qué es una pala.",
    bio: "Joven de alta sociedad porteña. Famosa por su inocencia y vida de lujos.",
    lore: "Vivió 5 meses en la casa sin quedar nominada casi nunca gracias a su simpatía. Afuera protagonizó un escándalo familiar feroz entre su madre Aixa y su novio Manuel por el manejo de su dinero.",
    image: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=500&auto=format&fit=crop&q=80",
    auraScore: 8.0,
    caretaScore: 4.0
  },
  {
    id: "cristian-u",
    name: "Cristian U (Cristian Urrizaga)",
    category: "gh",
    categoryLabel: "Gran Hermano / Leyenda Prócer",
    tag: "El Inventor de la Auto-Nominación",
    quote: "¡No toquen nada, carajo! Esto es estrategia.",
    bio: "Paseador de perros que se consagró como el mejor jugador táctico de la historia de GH (2011).",
    lore: "Inventó la 'autonominación' para obligar a su fandom a eliminar a sus rivales uno por uno. Se fue de la casa, el público exigió su regreso y ganó el programa arrasando. Hoy DJ internacional y panelista filoso.",
    image: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=500&auto=format&fit=crop&q=80",
    auraScore: 9.8,
    caretaScore: 2.0
  },
  {
    id: "marianela-mirra",
    name: "Marianela Mirra",
    category: "gh",
    categoryLabel: "Gran Hermano / La Reina de la Espontánea",
    tag: "La Traición Perfecta a Diego Leonardi",
    quote: "Hice lo que sentí que tenía que hacer para ganar.",
    bio: "Ganadora de GH 2007 tras clavarle la espontánea a su amigo y protector Diego Leonardi.",
    lore: "Autora de la traición más recordada de la televisión argentina. Se hizo la víctima durante todo el encierro, esperó la semifinal y liquidó a Diego Leonardi con una espontánea maestra. Años después filtró chats íntimos de Jorge Rial.",
    image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=500&auto=format&fit=crop&q=80",
    auraScore: 9.5,
    caretaScore: 6.0
  },
  {
    id: "gaston-trezeguet",
    name: "Gastón Trezeguet",
    category: "gh",
    categoryLabel: "Gran Hermano / Productor & Panelista",
    tag: "El Estratega Original de 2001",
    quote: "Gran Hermano es un juego de ajedrez humano.",
    bio: "Finalista de la primera edición de GH (2001) y productor general del formato en Kuarzo.",
    lore: "Pionero absoluto de las estrategias psicológicas en la televisión argentina: escondió comida, fingió pactos y revolucionó el juego. Hoy es el panelista más respetado y temido de 'El Debate'.",
    image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=500&auto=format&fit=crop&q=80",
    auraScore: 9.2,
    caretaScore: 3.5
  },
  {
    id: "andrea-rincon",
    name: "Andrea Rincón",
    category: "gh",
    categoryLabel: "Gran Hermano / Actriz Consagrada",
    tag: "La Leona del Arrabal",
    quote: "Dejé todo en el barro para ser quien soy hoy.",
    bio: "Ex GH 2007, vedette furor, ganadora del Premio Martín Fierro y actriz de ficción dramática.",
    lore: "Surgió con peleas históricas en GH y Showmatch, superó adicciones complejas, se bautizó en la iglesia evangélica y demostró una capacidad actoral descomunal en series de televisión y cine.",
    image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=500&auto=format&fit=crop&q=80",
    auraScore: 9.3,
    caretaScore: 1.8
  },
  {
    id: "silvina-luna",
    name: "Silvina Luna (Inmortal)",
    category: "gh",
    categoryLabel: "Gran Hermano / Ícono Eterno",
    tag: "El Baile del Meneíto & Luz Eterna",
    quote: "Vivan con amor, perdonen y cuiden su salud.",
    bio: "Subcampeona de GH 2001, actriz, modelo y símbolo de la lucha contra la mala praxis médica.",
    lore: "Conquistó el corazón de los argentinos con su baile del 'Meneíto' y su frescura rosarina. Su trágica muerte tras años de lucha contra las consecuencias de las cirugías de Aníbal Lotocki unió al país en un reclamo unánime de justicia.",
    image: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=500&auto=format&fit=crop&q=80",
    auraScore: 10.0,
    caretaScore: 0.5
  }
];

// Helper to append remaining categories up to exactly 200
console.log("Current count:", CELEBRITIES.length);
`);
