const fs = require('fs');
const path = require('path');

const celebrities = [
  // ==========================================
  // 1. MESA PRENDIDO FUEGO & LORE DE LA CASA
  // ==========================================
  {
    id: "tomas-holder",
    name: "Tomás Holder",
    category: "gh",
    categoryLabel: "Prendido Fuego / Gym Bro",
    tag: "Macho Alfa de Rosario",
    quote: "Mi mujer no es un hotel, es un hogar.",
    bio: "Primer expulsado y más icónico de GH. Amante de la noche, anabólicos, mewing y soltar factos cancelables.",
    lore: "El rey del contenido divisivo. Saltó a la fama en TikTok mostrando su físico y un personaje de rugbier clasista. Tras GH protagonizó romances escandalosos, internaciones por excesos, videos íntimos filtrados y una transformación espiritual que convive con su ego de gimnasio.",
    image: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=500&auto=format&fit=crop&q=80",
    auraScore: 7.8,
    caretaScore: 8.5
  },
  {
    id: "diane-caracchi",
    name: "Diane Caracchi",
    category: "farandula",
    categoryLabel: "Prendido Fuego / Conductora",
    tag: "El Ancla Moral & Monógama",
    quote: "Sos un cinco códigos, Tomás.",
    bio: "Modelo y estudiante de RR.PP. 8 años de novia, 2 de convivencia. Defensora a ultranza de la fidelidad.",
    lore: "Representa la voz de la razón y los límites inquebrantables en la mesa. No le perdona una sola infidelidad a la farándula, destruye a los jugadores de fútbol sin códigos y le pone los puntos a Holder cada vez que derrapa al aire.",
    image: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=500&auto=format&fit=crop&q=80",
    auraScore: 9.1,
    caretaScore: 2.3
  },
  {
    id: "luli-case",
    name: "Luli Casé Rossi",
    category: "farandula",
    categoryLabel: "Prendido Fuego / Conductora",
    tag: "La Migajera con Tarot",
    quote: "Esperé 2 años a un pibe y se comió a otra en Miami.",
    bio: "Conductora histriónica, astróloga de cabecera y experta en conformarse con migajas de amor por idealización.",
    lore: "El corazón sensible de Prendido Fuego. Conoce todas las red flags porque cayó en todas. Tira las cartas del tarot en vivo, analiza las cartas natales de los famosos y confiesa sus fracasos amorosos sin filtro para salvar a las oyentes.",
    image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=500&auto=format&fit=crop&q=80",
    auraScore: 8.9,
    caretaScore: 1.8
  },
  {
    id: "gisela-holder",
    name: "Gisela Gordillo (Mamá de Holder)",
    category: "farandula",
    categoryLabel: "Prendido Fuego / Lore",
    tag: "La Señora de los Factos",
    quote: "A los hombres hay que tenerlos cortitos.",
    bio: "Podóloga de Rosario, madre de Tomás y protagonista de rumores picantes con mediáticos.",
    lore: "Se convirtió en una estrella mediática propia durante el paso de Tomás por GH. Su fuerte personalidad, belleza y romances con figuras del espectáculo (como Martín Ku y mediáticos porteños) revolucionaron los programas de chimentos.",
    image: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=500&auto=format&fit=crop&q=80",
    auraScore: 8.4,
    caretaScore: 6.9
  },

  // ==========================================
  // 2. FARÁNDULA, DIVAS, MEDIÁTICOS & BOTINERAS
  // ==========================================
  {
    id: "wanda-nara",
    name: "Wanda Nara",
    category: "farandula",
    categoryLabel: "Farándula / Botinera Queen",
    tag: "Reina del Marketing & Chimento",
    quote: "Las mujeres ya no lloran, las mujeres facturan millones.",
    bio: "Empresaria, conductora y dueña del 90% de los escándalos mediáticos de Argentina e Italia.",
    lore: "Inventora de la profesión botinera moderna y maestra del timing mediático. De la supuesta virginidad con Maradona a negociar los contratos de Mauro Icardi en el Inter y PSG, pasando por su romance tóxico con L-Gante y su guerra fría con La China Suárez.",
    image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=500&auto=format&fit=crop&q=80",
    auraScore: 9.8,
    caretaScore: 9.5
  },
  {
    id: "mauro-icardi",
    name: "Mauro Icardi",
    category: "futbol",
    categoryLabel: "Fútbol / Botinero",
    tag: "El Tatuado de Estambul",
    quote: "Ella es mi esposa, mi vida y mi único amor.",
    bio: "Goleador del Galatasaray, ex capitán del Inter y protagonista del culebrón más largo del siglo.",
    lore: "Pasó de traicionar a Maxi López a ser vigilado 24/7 por Wanda. Famoso por subir fotos románticas de alta intensidad en Instagram minutos después de que Wanda anuncia su separación por historias.",
    image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=500&auto=format&fit=crop&q=80",
    auraScore: 6.5,
    caretaScore: 8.9
  },
  {
    id: "china-suarez",
    name: "La China Suárez",
    category: "farandula",
    categoryLabel: "Farándula / Actriz",
    tag: "Terror de los Matrimonios",
    quote: "Yo soy libre y hago lo que quiero con mi vida.",
    bio: "Actriz, cantante, imán mediático internacional y pesadilla de los chats de botineras.",
    lore: "Figura magnética que protagonizó los mayores quiebres de parejas del país: Cabré-Tobal, Vicuña-Pampita (motorhome y manta de Nepal), y el Wandagate en París. No pide disculpas ni da explicaciones a la prensa tradicional.",
    image: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=500&auto=format&fit=crop&q=80",
    auraScore: 9.5,
    caretaScore: 7.2
  },
  {
    id: "pampita",
    name: "Carolina 'Pampita' Ardohain",
    category: "farandula",
    categoryLabel: "Farándula / Conductora",
    tag: "Sonrisa Blindada a 4K",
    quote: "Te destruyo en vivo pero con una sonrisa perfecta.",
    bio: "Supermodelo y estratega máxima. Se separa de un político y a los 3 días ya tiene nuevo novio polista.",
    lore: "La mujer más amada y respetada del espectáculo. Capaz de atravesar tragedias inmensas, infidelidades en motorhomes y escándalos políticos de García Moritán, saliendo siempre ilesa, impecable y cobrando fortunas en dólares por presencia.",
    image: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=500&auto=format&fit=crop&q=80",
    auraScore: 10.0,
    caretaScore: 5.0
  },
  {
    id: "yanina-latorre",
    name: "Yanina Latorre",
    category: "farandula",
    categoryLabel: "Farándula / LAM Queen",
    tag: "Francotiradora de Chats",
    quote: "Tengo los chats y los audios, amor. No me busques.",
    bio: "La voz más temida del espectáculo. Sabe con quién te fuiste de fiesta antes de que vos llegues.",
    lore: "Reina de la primicia destructiva. Conduce su programa de radio y domina LAM con información directa de los teléfonos de los protagonistas. Si te metés con ella, te destapa una infidelidad de hace 10 años en horario central.",
    image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=500&auto=format&fit=crop&q=80",
    auraScore: 9.6,
    caretaScore: 4.1
  },
  {
    id: "moria-casan",
    name: "Moria Casán",
    category: "farandula",
    categoryLabel: "Farándula / La One",
    tag: "Lengua Karateca Prócer",
    quote: "Si querés llorar, llorá. ¡Decorado, callate!",
    bio: "Máxima deidad del espectáculo. Inventora del léxico pop argentino y blindada contra todo.",
    lore: "Medio siglo reinando el teatro de revistas, televisión y streaming. Creadora de frases como 'el decorado se calla', 'lengua karateca' y 'billetera mata galán'. Nada la cancela, nada la incomoda y siempre tiene la última palabra.",
    image: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=500&auto=format&fit=crop&q=80",
    auraScore: 10.0,
    caretaScore: 1.0
  },
  {
    id: "susana-gimenez",
    name: "Susana Giménez",
    category: "farandula",
    categoryLabel: "Farándula / Diva Nacional",
    tag: "La Diva del Teléfono & Dólar",
    quote: "¿Vivo? ¡Un dinosaurio vivo!",
    bio: "La diva número uno de la historia argentina. Millonaria en Punta del Este y despistada profesional.",
    lore: "Ícono indiscutido de la televisión dorada. Famosa por sus preguntas inocentes pero letales, su cenicero arrojado a Huberto Roviralta, sus juegos telefónicos millonarios y sus declaraciones espontáneas sin filtro político.",
    image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=500&auto=format&fit=crop&q=80",
    auraScore: 9.9,
    caretaScore: 6.0
  },
  {
    id: "l-gante",
    name: "L-Gante (Elián Valenzuela)",
    category: "musica",
    categoryLabel: "Música / RKT & Cumbia 420",
    tag: "El Rey de General Rodríguez",
    quote: "Cumbia 420 pa los negros, keloke.",
    bio: "Creador de la Cumbia 420. Estuvo preso 100 días, tiene juicio oral y sale con Wanda Nara.",
    lore: "Pasó de grabar canciones con una netbook del gobierno a tener caravanas de autos de lujo y limusinas ploteadas. Su romance intermitente con Wanda Nara enardeció a Mauro Icardi y divide a las redes sociales entre amor genuino y marketing brutal.",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&auto=format&fit=crop&q=80",
    auraScore: 9.3,
    caretaScore: 3.5
  },
  {
    id: "angel-de-brito",
    name: "Ángel de Brito",
    category: "farandula",
    categoryLabel: "Farándula / Conductor LAM",
    tag: "El Cirujano del Espectáculo",
    quote: "Tengo un último momento que va a paralizar el país.",
    bio: "Conductor de LAM y zar del chimento argentino. Controla las primicias del prime time.",
    lore: "El cerebro detrás del formato de panelismo más exitoso de los últimos 10 años. Maneja las primicias con puño de hierro, no se casa con nadie y administra los egos de sus 'angelitas' como un director de orquesta de barro.",
    image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=500&auto=format&fit=crop&q=80",
    auraScore: 8.8,
    caretaScore: 5.5
  },
  {
    id: "charlotte-caniggia",
    name: "Charlotte Caniggia",
    category: "farandula",
    categoryLabel: "Farándula / Reality Star",
    tag: "Shampein & Cero Drama",
    quote: "Yo no trabajo, me gusta el shampein y dormir.",
    bio: "Hija del Pájaro Caniggia y Mariana Nannis. Reina de la sinceridad bizarra y el humor involuntario.",
    lore: "Cada vez que pisa un reality o un stream genera momentos de culto instantáneos. No le interesa la corrección política, admite que odia cocinar y madrugar, y dice al aire lo que todo el mundo piensa en privado.",
    image: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=500&auto=format&fit=crop&q=80",
    auraScore: 9.4,
    caretaScore: 1.2
  },
  {
    id: "alex-caniggia",
    name: "Alex Caniggia (El Emperador)",
    category: "farandula",
    categoryLabel: "Farándula / Showman",
    tag: "El Emperador del Baratismo",
    quote: "¡Siempre al top, nunca barat!",
    bio: "Ganador de realities en Argentina y España. Enemigo jurado de los 'barats' y maestro del bardo.",
    lore: "Personaje ruidoso, ostentoso y magnético. Ganó El Hotel de los Famosos, fue padre con Melody Luz y mantiene una guerra mediática eterna con su padre Claudio Caniggia por defender a su madre Mariana Nannis.",
    image: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=500&auto=format&fit=crop&q=80",
    auraScore: 8.1,
    caretaScore: 8.8
  },
  {
    id: "carmen-barbieri",
    name: "Carmen Barbieri",
    category: "farandula",
    categoryLabel: "Farándula / Conductora",
    tag: "La Leona del Teatro",
    quote: "¡Yo no soy una carmelita descalza, mi amor!",
    bio: "Capocómica histórica, conductora de Mañanísima y madre de Fede Bal.",
    lore: "Toda su vida privada fue transmitida en cadena nacional: la infidelidad de Santiago Bal con Ayelén Paleo, los escándalos del lavarropas inteligente de Fede Bal y sus internaciones dramáticas. Cero careta, puro show teatral.",
    image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=500&auto=format&fit=crop&q=80",
    auraScore: 8.7,
    caretaScore: 4.8
  },
  {
    id: "nazarena-velez",
    name: "Nazarena Vélez",
    category: "farandula",
    categoryLabel: "Farándula / Panelista",
    tag: "Sobreviviente Mediática",
    quote: "Pasé por el infierno y volví para contarlo.",
    bio: "Productora teatral, ex vedette furor de los 2000 y panelista estrella de LAM.",
    lore: "Vivió todas las tragedias y batallas de la farándula argentina. Hoy reciclada como panelista sensata y frontal, se ríe de sus romances pasados y no le tiene miedo a ninguna figura pública.",
    image: "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=500&auto=format&fit=crop&q=80",
    auraScore: 8.9,
    caretaScore: 2.5
  },
  {
    id: "cinthia-fernandez",
    name: "Cinthia Fernández",
    category: "farandula",
    categoryLabel: "Farándula / Mediática & Abogada",
    tag: "El Terror de Matías Defederico",
    quote: "A mí me vas a pagar la cuota alimentaria hasta el último peso.",
    bio: "Bailarina, panelista y pareja del abogado Roberto Castillo. Cruzada contra los padres deudores.",
    lore: "Convirtió su conflicto judicial por alimentos en una causa nacional, ganándole todas las batallas a su ex marido futbolista. Frontal, hiperactiva y sin miedo al juicio mediático ni a las cartas documento.",
    image: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=500&auto=format&fit=crop&q=80",
    auraScore: 8.5,
    caretaScore: 5.2
  },
  {
    id: "nicole-neumann",
    name: "Nicole Neumann",
    category: "farandula",
    categoryLabel: "Farándula / Top Model",
    tag: "La Rubia Vegana de la Pampa",
    quote: "La paz y los animales son mi prioridad absoluta.",
    bio: "Top model histórica, rival legendaria de Pampita y esposa del piloto Manu Urcera.",
    lore: "Rivalidad mítica con Pampita durante más de dos décadas en las pasarelas. Enfrentamientos con Cubero y Mica Viciconte por sus hijas, y un estilo de vida vegano y espiritual blindado contra el barro de la tele.",
    image: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=500&auto=format&fit=crop&q=80",
    auraScore: 7.9,
    caretaScore: 7.5
  },
  {
    id: "flor-de-la-v",
    name: "Flor de la V",
    category: "farandula",
    categoryLabel: "Farándula / Conductora Intrusos",
    tag: "La Gran Dama de la Tarde",
    quote: "¡Bienvenidos a Intrusos en el Espectáculo!",
    bio: "Conductora de Intrusos, actriz de comedia e ícono histórico del colectivo LGBTIQ+ en Argentina.",
    lore: "Conquistó el teatro de revista, el prime time con Los Roldán y la conducción del programa insignia del chimento argentino. Conduce con elegancia, alta costura y un manejo quirúrgico de los tiempos televisivos.",
    image: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=500&auto=format&fit=crop&q=80",
    auraScore: 9.0,
    caretaScore: 6.2
  },
  {
    id: "laurita-fernandez",
    name: "Laurita Fernández",
    category: "farandula",
    categoryLabel: "Farándula / Conductora & Bailarina",
    tag: "La Chica Perfecta de la Tele",
    quote: "El talento y el ensayo no se negocian.",
    bio: "Bailarina virtuosa, actriz de musicales y conductora estrella de El Trece y El Nueve.",
    lore: "Surgió de Combate y Showmatch para convertirse en la figura joven más completa de la pantalla. Romances con Fede Bal, Nicolás Cabré y Peluca Brusca, combinando un perfil profesional intachable con tapas de revistas del corazón.",
    image: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=500&auto=format&fit=crop&q=80",
    auraScore: 8.6,
    caretaScore: 4.5
  },
  {
    id: "graciela-alfano",
    name: "Graciela Alfano",
    category: "farandula",
    categoryLabel: "Farándula / Sex Symbol Inmortal",
    tag: "El Mito Erótico Argentino",
    quote: "A mí me gusta gustar, no tengo edad ni vergüenza.",
    bio: "La mujer más deseada del cine nacional de los 80, ex jurado del Bailando y dueña de un aura indestructible.",
    lore: "Romances con presidentes, estrellas de fútbol (Maradona), y galanes de todas las épocas (Matías Alé). Maneja Twitter e Instagram con una soltura de Generación Z, mostrando un cuerpo escultural y provocando debates intergeneracionales.",
    image: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=500&auto=format&fit=crop&q=80",
    auraScore: 9.7,
    caretaScore: 5.0
  },
  {
    id: "marcelo-tinelli",
    name: "Marcelo Tinelli",
    category: "farandula",
    categoryLabel: "Farándula / Zar de la TV",
    tag: "El Cabezón de Bolívar",
    quote: "¡Buenas noches América! ¡Señores, esto es Showmatch!",
    bio: "El conductor más exitoso de los últimos 35 años de televisión en Argentina.",
    lore: "Moldeó la cultura popular argentina durante tres décadas: el corte de pollera, las peleas en el barro del Bailando, el fútbol en San Lorenzo y la AFA. Actualmente en pareja con Milett Figueroa y buscando reconquistar al público digital.",
    image: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=500&auto=format&fit=crop&q=80",
    auraScore: 8.5,
    caretaScore: 8.7
  },
  {
    id: "jorge-rial",
    name: "Jorge Rial",
    category: "farandula",
    categoryLabel: "Farándula / Periodista de Choque",
    tag: "El Fundador de Intrusos",
    quote: "Si hablo yo, se cae el sistema.",
    bio: "Creador de Intrusos, conductor de Argenzuela y sobreviviente a un paro cardíaco en Colombia.",
    lore: "Durante 20 años fue la persona con más poder para consagrar o destruir carreras en el espectáculo argentino. Su pase a la política, sus peleas con su hija Morena Rial y su renacimiento en C5N lo mantienen en el centro de la tormenta.",
    image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=500&auto=format&fit=crop&q=80",
    auraScore: 8.0,
    caretaScore: 7.9
  },
  {
    id: "luciana-salazar",
    name: "Luciana Salazar (Luli Pop)",
    category: "farandula",
    categoryLabel: "Farándula / Mediática & Geopolítica",
    tag: "La Tuitera de la Política Oculta",
    quote: "Tengo información de primerísima fuente sobre las medidas del Banco Central.",
    bio: "Modelo icónica, madre de Matilda y enemiga pública número uno de Martín Redrado.",
    lore: "Sorprendió al país filtrando primicias políticas y económicas en Twitter antes que los diarios especializados. Su juicio eterno con el economista Martín Redrado por la manutención de su hija es un culebrón sin fin.",
    image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=500&auto=format&fit=crop&q=80",
    auraScore: 7.7,
    caretaScore: 8.6
  },
  {
    id: "vicky-xipolitakis",
    name: "Vicky Xipolitakis (La Griega)",
    category: "farandula",
    categoryLabel: "Farándula / Mediática Surrealista",
    tag: "La Griega del Vuelo Austral",
    quote: "¡Soy una nena que vive en una nube de algodón!",
    bio: "Reina del disparate televisivo, ex MasterChef Celebrity y madre de Salvador Uriel.",
    lore: "Autora de los momentos más insólitos de la historia nacional: pilotear un avión de Austral en pleno despegue, vestirse de billetes en el subte de Nueva York y cocinar con inocencia infantil en MasterChef. Todo en ella es inverosímil.",
    image: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=500&auto=format&fit=crop&q=80",
    auraScore: 8.9,
    caretaScore: 3.0
  },
  {
    id: "felipe-fort",
    name: "Felipe Fort",
    category: "farandula",
    categoryLabel: "Farándula / Heredero Fort",
    tag: "El Heredero del Chocolate & Marcas",
    quote: "Mi papá me enseñó a no tenerle miedo a los números grandes.",
    bio: "Hijo mellizo del legendario Ricardo Fort. Inversor en criptomonedas, autos de lujo y marcas.",
    lore: "Creció bajo la mirada de todo el país como el hijo del 'Comandante'. Apenas cumplió los 18 años tomó el control de sus inversiones en Miami, modificó las recetas de los chocolates familiares y mantiene viva la leyenda de su padre con perfil bajo pero millonario.",
    image: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=500&auto=format&fit=crop&q=80",
    auraScore: 8.7,
    caretaScore: 3.8
  },
  {
    id: "marta-fort",
    name: "Marta Fort",
    category: "farandula",
    categoryLabel: "Farándula / Heredera Fort",
    tag: "La Hija del Comandante",
    quote: "Tengo la personalidad de mi papá: voy de frente contra todo.",
    bio: "Heredera de la dinastía Felfort, influencer de moda y guardiana de la memoria de Ricardo.",
    lore: "Heredó la mirada imponente y el carácter frontal de Ricardo Fort. Frecuenta eventos de alta moda, festivales de música electrónica en el mundo y se planta ante los panelistas de televisión con una madurez que impresiona.",
    image: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=500&auto=format&fit=crop&q=80",
    auraScore: 8.8,
    caretaScore: 2.9
  }
];

// Helper to generate full list of 200 figures with deep Argentine relevance
console.log("Seed count:", celebrities.length);
